prometheus-community/ipmi_exporter

README.md
collector.go

Instead of failing hard and not returning any metrics at all if just one
(or two) of the three calls to IPMI tools fail, return whatever data was
properly received and add a `collector` label to the `ipmi_up` metric
indicating which tools failed.
This is only a small step towards the concept of "collectors" like they
exist e.g. in the node exporter, but it should help solve #1. Additional
functionality, like disabling certain collectors, can be built on top of
this.

Handle tool-specific failures more gracefully

---

README.md
collector.go
main.go

This enables the standard `/metrics` endpoint. A scrape will trigger the
collection of IPMI metrics from the local machine (that the exporter is
running on).
@grobie @beorn7 please scrutinize.

Support collecting local IPMI metrics

---

collector.go

Thanks for sharing this awesome tool!
We are using it mostly for getting remote ipmi metrics via RMCP, and found it a bit tricky to correlate some errors to the actual target that is failing.
Hope you'll find this small PR useful, helped us fix some issues with our hosts.
/cc @bitfehler

Add rmcp host info to log messages

---

collector.go
config.go
ipmi_remote.yml

Now that we have a good config framework in place, this is low-hanging
fruit. Will apply to all collectors used, so total scrape time for
Prometheus could be (timeout * #-of-collectors) milliseconds for a given
module.
Related to #20.

Allow setting the session timeout

---

collector.go

Hi,
while i was testing this exporter
if i run this command on one host
./ipmimonitoring -Q -b --comma-separated-output --output-sensor-state
the result would be
...... 32,PS Status,Power Supply,Nominal,N/A,N/A,'OK'
and Ipmi exporter will report
ipmi_sensor_state{id="32",name="PS Status",type="Power Supply"} 0
which is totally fine and correct
however on some old BMC's running the command :
./ipmimonitoring -Q -b --comma-separated-output --output-sensor-state
will give
1813,PS Status,Power Supply,N/A,N/A,N/A,'Presence detected' 'Unrecognized Event = 0100h' 'Unrecognized Event = 0200h' 'Unrecognized Event = 0400h' 'Unrecognized Event = 0800h' 'Unrecognized Event = 1000h' 'Unrecognized Event = 2000h' 'Unrecognized Event = 4000h'
and thus ipmi exporter will report …

No sensor state for PSU sensor on old BMC's 

---

Dockerfile
README.md
docker-compose.yml

Added Dockerfile for ipmi_exporter, along with a simple docker-compose.yml. README.md has also been updated with instructions for getting ipmi_exporter up and running with docker-compose.

Added Dockerfile and example docker-compose.yml

---

README.md
collector.go
config.go
ipmi_local.yml
ipmi_remote.yml

I found that I had the need to track which machines were in the poweron / off state.
To do so, I extended ipmi_exporter to use the ipmi-chassis module
The new metric added is ipmi_chassis_power_state
The ipmi-chassis utility does export more results, but so far this is the only one I needed.
I thought this may be useful for others.

Ipmi-chassis power on/off state

---

collector.go
config.go
ipmi_remote.yml

Provides a way to specify in the config file `workaround_flags` to be passed onto FreeIPMI.
I needed this to pass in a flag due to a known issue with HP ProLiant servers:
tps://www.gnu.org/software/freeipmi/freeipmi-faq.html#Why-is-the-output-from-FreeIPMI-different-than-another-software_003f
Thought this might be of interest to others as well for different workaround flags needed for their systems.

Adding config options for workaround_flags.

---

collector.go

See the individual commit messages for details.
Fixes #57

Use partial bmc-info output even if it fails

---

Dockerfile

Sorry about the previous Issue #59,
It seems the docker's bug or something, and it has already fixed.
So, could you update the DockerFile again please ?
- Bug
docker build . 
(or make docker)
https://github.com/soundcloud/ipmi_exporter/issues/59#issuecomment-781759774
go builder in docker makes ipmi_exporter as `ipmi_exporter` again.
```
>> running check for unused packages in vendor/
GO111MODULE=on go mod vendor
curl -s -L https://github.com/prometheus/promu/releases/download/v0.5.0/promu-0.5.0.linux-amd64.tar.gz | tar -xvzf - -C /tmp/tmp.3HO4rjwbn0
promu-0.5.0.linux-amd64/
promu-0.5.0.linux-amd64/promu
promu-0.5.0.linux-amd64/NOTICE
promu-0.5.0.linux-amd64/LICENSE
mkdir -p /go/bin
cp /tmp/tmp.3HO4rjwbn0/promu-0.5.0.linux-amd64/promu /go/bin/promu
rm -r /tmp/tmp.3HO4rjwbn0
>> building …
```

Failed COPY ipmi_exporter from=builder - again

---

ipmi_remote.yml

I just had an issue, where the dcmi collector returned:
```
ipmi_ctx_open_outofband_2_0: invalid parameters
```
It was because I set the timeout to `1000`, but this was too low since it has to be greater than `retransmission-timeout` which defaults to 1000:
https://www.gnu.org/software/freeipmi/manpages/man8/ipmi-dcmi.8.html
This PR documents this configuration subtlety

doc: timeout must be greater than 1000

---

collector_ipmi.go
freeipmi/freeipmi.go

Instead of this:
```
level=debug ts=2021-11-09T05:12:58.244Z caller=freeipmi.go:139 msg=Executing command=ipmimonitoring args="unsupported value type"
level=debug ts=2021-11-09T05:12:58.475Z caller=collector_ipmi.go:161 msg="Got values" data="unsupported value type"
```
You get this now:
```
level=debug ts=2021-11-09T05:41:58.307Z caller=freeipmi.go:139 msg=Executing command=ipmimonitoring args="[--entity-sensor-names --record-ids=<...> -Q --ignore-unrecognized-events --comma-separated-output --no-header-output --sdr-cache-recreate --output-event-bitmask --config-file <...> -h <...>]"
level=debug ts=2021-11-09T05:41:58.542Z caller=collector_ipmi.go:162 msg="Got values" data="{ID:91 Name:Power Supply 1 Current 1 Type:Current State:Nominal Value:1.4 Unit:A Event:00C0h}"
```

fix unsupported value type in debug logs due to attempting to log structs directly

---

collector_ipmi.go
docs/metrics.md

Fan sensors on HP servers report speed as a percentage of the maximum instead of a raw RPM value, for example:
```
% sudo ipmi-sensors --sensor-types=Fan
ID | Name            | Type | Reading    | Units | Event
57 | Fan 1           | Fan  | N/A        | N/A   | 'transition to Running'
58 | Fan 1 DutyCycle | Fan  | 21.95      | %     | 'OK'
59 | Fan 1 Presence  | Fan  | N/A        | N/A   | 'Device Inserted/Device Present'
60 | Fan 2           | Fan  | N/A        | N/A   | 'transition to Running'
61 | Fan 2 DutyCycle | Fan  | 27.83      | %     | 'OK'
62 | Fan 2 Presence  | Fan  | N/A        | N/A   | 'Device Inserted/Device Present'
63 | Fan 3           | Fan  | N/A        | N/A   | 'transition to Running'
64 | Fan 3 DutyCycle | Fan  | 27.83      | %     | 'OK'
65 | Fan 3 Presence  | Fan …
```

Add support for fan sensors which report as a percentage

---

main.go

Without this, the log.level flag is ignored, and everything (including debug) is logged.
promlogConfig does not need to be a global var either.

Instantiate logger after parsing log.level command-line flag

---

collector.go
collector_ipmi.go

When we need to debug special target on exporter among dozens of hosts - target is necessary for greps

Added target to debug logs

---

collector_ipmi.go

I received an error collection ipmi sensors status, because my output table is missing status column. It can be added by the argument according to `--help` information.

Add `--output-sensor-state` argument to ipmi-sensors command

---

collector_chassis.go
freeipmi/freeipmi.go

Recently we started using ipmi_exporter and found out that there is no metrics for cooling fault and drive fault. 
So we added some.
Link to the issue: https://github.com/prometheus-community/ipmi_exporter/issues/144

Add chassis cooling fault and drive fault metrics

---

CHANGELOG.md
collector_dcmi.go
docs/metrics.md
freeipmi/freeipmi.go

Added DCMI metric to definitely determine avail of Power Measurement feature
In some cases, for example with cheap Power Supply Units power consumption may be not available at all, to control this added `ipmi_dcmi_power_measurement_state` metric. The value is `1` for power measure is available on, and `0` otherwise.
The main point for this changes is a try to knowledge: the measurements isn't accessed due PSU broken (FW/cable/etc issues) or not avail at all on system level (and system know about that) 
The host with "normal PSU":
```ruby
root@host# curl -Ss "http://127.0.0.1:9291/ipmi?module=default&target=10.249.0.9" | grep -i dcmi
ipmi_dcmi_power_consumption_watts 353
ipmi_dcmi_power_measurement_state 1
ipmi_up{collector="dcmi"} 1
```
The host with "strange PSU's"
```ruby
root@host# …
```

Added Power Measurement State to DCMI collector

---

collector_bmc_watchdog.go
config.go
docs/metrics.md
freeipmi/freeipmi.go
ipmi_local.yml
ipmi_remote.yml

Our supermicro BMC's provide a watchdog functionality, i.e. taking some specified action if a timer is not reset within a specified time. freeipmi tools have a bmc-watchdog command to control and also report the current status of such function. This collector reports that information.
An example output for bmc-watchdog from freeipmi:
```
$ sudo bmc-watchdog --get
Timer Use:                   BIOS FRB2
Timer:                       Running
Logging:                     Enabled
Timeout Action:              Power Cycle
Pre-Timeout Interrupt:       None
Pre-Timeout Interval:        1 seconds
Timer Use BIOS FRB2 Flag:    Clear
Timer Use BIOS POST Flag:    Clear
Timer Use BIOS OS Load Flag: Clear
Timer Use BIOS SMS/OS Flag:  Clear
Timer Use BIOS OEM Flag:     Clear
Initial Countdown: …
```

Bmc watchdog

---

collector_sel_events.go
config.go
docs/metrics.md
freeipmi/freeipmi.go
ipmi_local.yml
ipmi_remote.yml

Added a new collector to collect custom metrics from SEL events via IPMI.
In config metrics are defined in this format:
```yml
modules:
default:
collectors:
...
- sel-events
sel_events:
- name: correctable_memory_error
regex: Correctable memory error.*
```
Metrics are shown as:
```
ipmi_sel_events_count_by_state{state="Nominal"} 12
ipmi_sel_events_count_by_state{state="Warning"} 128
ipmi_sel_events_count_by_name{name="correctable_memory_error"} 140
ipmi_sel_events_latest_timestamp{name="correctable_memory_error"} 1.704979201e+09
```
Closes #41

feat: custom SEL events metrics

---

Dockerfile
Makefile
README.md

This is a pretty trivial fix to bring back arm64
builds and this has been tested locally as well.
Closes: #103

fix: bring back aarch64 builds

---

collector_bmc.go
freeipmi/freeipmi.go

@SuperQ Hi!
Please review the PR. I need to add URL info from BMC.
Actual output from console
```bash
BMC URL                       : https://123.234.21.231:443
```

feat: add bmc url

---

collector_ipmi.go
collector_sel_events.go

Hi, FreeIPMI maintainer here.  A user reported a potential issue with the FreeIPMI master branch.    I don't use prometheus so this fix is going off code inspection only and is untested.
---
Problem: The short option -Q for "quiet cache" was legacied in FreeIPMI in early 2018.  It has the potential to be removed some day in the future.
Solution: Use the long option --quiet-cache instead.

Use long option for quiet cache

---

main.go

To find out which version of the IPMI Exporter is running, add the VersionCollector from the Prometheus Golang Client.
We use the build info metrics to see if our maintained exporters need updates. The metric was lacking, so I went in and added it.

add the Version Collector Metric

---

collector_bmc_native.go

When I use native-IPMI to collect BMC metrics, the ipmi-exporter always panics. The related issues are: [#262](https://github.com/prometheus-community/ipmi_exporter/issues/262) and [#248 ](https://github.com/prometheus-community/ipmi_exporter/issues/248).
error info:
``` text
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x137bc9e]
goroutine 99 [running]:
github.com/bougou/go-ipmi.(*SystemInfoParams).ToSystemInfo(0xc00053b4f8)
/root/gotools/pkg/mod/github.com/bougou/go-ipmi@v0.7.2/types_system_info_params.go:101 +0x3e
```
The panic always occurs at github.com/bougou/go-ipmi.(*SystemInfoParams).ToSystemInfo. Looking at the corresponding code.
```go
func (systemInfoParams *SystemInfoParams) ToSystemInfo() …
```

FIX: panic in ipmi bmc native collector
